### ISSUE TITLE
Contact us form not working

### ISSUE THREAD

**Issue by pnijhara** [ieee-amu/ieee-amu#116]
@roshnet the contact us form that you designed isn't taking responses. Can you take a look at this please?

**Comment by roshnet** [comment]
Too busy with other stuff, might look into this later.

**Comment by pnijhara** [comment]
It's urgent, we nee your help.

**Comment by roshnet** [comment]
It wasn't an issue with the code. The security rules weren't properly set up. It works now.

**Comment by roshnet** [comment]
It wasn't an issue with the code. The security rules weren't properly set up. It works now.

**Comment by pnijhara** [comment]
Oh! I didn't check that. Thank you for your time.
