### ISSUE TITLE
Add logo to IEEE AMU

### ISSUE THREAD

**Issue by pnijhara** [ieee-amu/ieee-amu#17]
A logo which covers both AMU and IEEE.

**Comment by Slajnef** [comment]
Hello,
what kind of logo do you need? Thanks

**Comment by roshnet** [comment]
Hi @Slajnef, a logo size 48x48 (or larger) would be nice, preferably an SVG.

**Comment by Slajnef** [comment]
Hey, tell me what you think? :)

[Logo IEEE AMU.zip](https://github.com/ieee-amu/ieee-amu/files/4288707/Logo.IEEE.AMU.zip)

**Comment by pnijhara** [comment]
Hi @Slajnef, nice work! But we are looking for something more creative. Like a logo which covers both IEEE and AMU.

**Comment by Slajnef** [comment]
Hello, and now what do you think ? thanks

[Logo IEEE AMU.zip](https://github.com/ieee-amu/ieee-amu/files/4308014/Logo.IEEE.AMU.zip)
