### ISSUE TITLE
Add dark mode feature

### ISSUE THREAD

**Issue by pnijhara** [ieee-amu/ieee-amu#32]
Feature request: Add dark mode to the website. User can shift to dark mode by clicking on ieee-amu copyright tag in the footer.

**Comment by roshnet** [comment]
How would someone know that :copyright: is supposed to be clicked?

Should a toggle be added instead?

**Comment by pnijhara** [comment]
I think a small button at the footer near the social icons would be perfect for this.

**Comment by pnijhara** [comment]
@roshnet are you on this issue?
