### ISSUE TITLE
Add firebase support

### ISSUE THREAD

**Issue by pnijhara** [ieee-amu/ieee-amu#55]
Currently, every page is seeding the data in the form of objects from the scripts written after templates in every page.
This should be transferred to firebase so that every page can fetch data from there.

Recommended library:
- vuefire
- firebase
- vuexfire (optional)

**Comment by roshnet** [comment]
> every page is seeding the data in the form of objects from the scripts written after templates in every page.

Which specific page, and what data? An example would be appreciated.
Also, why state management? It's a simple website, can't see why would we need to maintain state.

**Comment by pnijhara** [comment]
Take a look at the blogs route https://github.com/ieee-amu/ieee-amu/blob/master/pages/blog.vue#L3-L55
Look how it is looping through all the data.
You can take a look at the data here &rarr; https://github.com/ieee-amu/ieee-amu/blob/master/pages/blog.vue#L60-L114

And yes we don't need Vuex.

**Comment by pnijhara** [comment]
Idea is to shift this data to firebase and then our vue page will fetch it from there.
Does that sounds good to you?

**Comment by roshnet** [comment]
Done in #77. Closing.
