### ISSUE TITLE
feature request: Integrate Calendar on index page

### ISSUE THREAD

**Issue by pnijhara** [ieee-amu/ieee-amu#58]
A calendar can be integrated that will dates and agendas from the firebase DB and show all the upcoming webinars on it.

Features:
- Can be modified using Firebase DB
- User can add the dates to their calendar by a single click.

**Comment by pnijhara** [comment]
@roshnet implementing calendar seems to be hard. @madhavm0706 can you do it by using Google calendar's API?

**Comment by madhavm0706** [comment]
For Google Calendar, we have to need Google Id

**Comment by pnijhara** [comment]
Will share that will you. But first, look if you are able to it or not.
