### ISSUE TITLE
Design custom contact form

### ISSUE THREAD

**Issue by pnijhara** [ieee-amu/ieee-amu#59]
Currently, we are using Mailchimp as our major email-fetching service. But this needs to be replaced.

Suggestions:
- Custom form for queries
- User can write his queries in the form and the form will either upload the data to the firebase or will directly mail the content to the ieee-amu's email.

Features:
- The customized form will look like other pages(using same colour scheme)
- No third party usage

**Comment by pnijhara** [comment]
@roshnet can I delete this issue?

**Comment by roshnet** [comment]
Yeah I think it's done, let's close it.
